Initial tests, lighthouse types, move UI code to TS and into its own file, links to Lighthouse HTML reports with screens
gtech-professional-services/tagspeed_audit pull request #42
Opened 2023-01-26 12:17 UTC by nenuadrian

Fixes https://github.com/gtech-professional-services/tagspeed_audit/issues/33 https://github.com/gtech-professional-services/tagspeed_audit/issues/34 https://github.com/gtech-professional-services/tagspeed_audit/issues/35

- [ ] Tests pass
- [ ] Appropriate changes to README are included in PR

2023-01-26 20:42 UTC, adamread requested changes
Couple of comment. Great work all together though! Really nice to see the tests started =)

2023-01-26 20:42 UTC, adamread commented on public/index.html
>        <br /><br />
Style - don't close void elements ([style guide](https://google.github.io/styleguide/htmlcssguide.html#Document_Type))

2023-01-26 20:42 UTC, adamread commented on public/index.html
> +            <p><label>URL</label></p>
The label either needs a for attribute or the input should be a child of it. Otherwise there's no connection.

2023-01-26 20:42 UTC, adamread commented on public/index.html
> +            <p><label>User Agent Override (optional)</label></p>
Same as above for the label.

2023-01-26 20:42 UTC, adamread commented on src/app.ts
> +    const maxUrlsToTry = parseInt((req.query.maxUrlsToTry ?? '10').toString());
It seems like we only try 10 URLs now. I'm not clear on why this is.

2023-01-26 20:42 UTC, adamread commented on src/core.ts
> +  for (const r of requests) {
We loop through all of the requests, even it we've already gone past the max number. Might it be better to just turn this into a standard for-loop?

2023-01-26 20:42 UTC, adamread commented on src/core.ts
> +      'Lighthouse did not return any metrics. The request may be blocked.'
A general best practice is to return the error from the library as well, so that the user can better see what the error encountered was.

2023-01-27 09:18 UTC, nenuadrian commented on src/app.ts
> +    const maxUrlsToTry = parseInt((req.query.maxUrlsToTry ?? '10').toString());
Sometimes there are too many - I'm adding the field in UI as well- next step will be to allow results to come as they are ready rather than at the end, otherwise you wait for a long time. It doesn't help with showcasing it, or for quick checks.

2023-01-27 13:34 UTC, adamread approved these changes
Great! LGTM

2023-01-27 13:34 UTC, adamread commented on src/app.ts
> +    const maxUrlsToTry = parseInt((req.query.maxUrlsToTry ?? '10').toString());
This doesn't leave an option for doing all of them though, unless you know how many requests are made in total before you start.

Also, the URLs are FIFO ordered, so just doing the first 10 might mean a major problem is left out.

2023-01-27 13:35 UTC, merged