Angular onboarding
gtech-professional-services/tagspeed_audit pull request #79
Opened 2023-06-08 13:58 UTC by nenuadrian

![image](https://github.com/google-marketing-solutions/tagspeed_audit/assets/5632882/618d246c-37fd-41fd-a4b9-72ed8c15ad89)

2023-06-13 06:44 UTC, adamread requested changes
A fix is needed in the server package.json. I think it would be nice if the tests were ported over and the change in score added back in too.

2023-06-13 06:44 UTC, adamread commented on server/package.json
>      "build": "rm -rf dist && tsc && cp -R public/** dist",
The cp needs to be removed for this to work, since the public dir has been removed.

2023-06-13 06:44 UTC, adamread commented on ui/src/app/app.component.spec.ts
It would be great if all of the tests from the non-angular version could be brought over to this version.

2023-06-13 06:44 UTC, adamread commented on ui/src/app/app.component.html
> +          <ng-container matColumnDef="lcp">
The change in the score has disappeared. You should be able to pass the baseline audit as a field in the AuditExecution type to be able to retrieve it again?

2023-06-26 10:50 UTC, nenuadrian commented on server/package.json
>      "build": "rm -rf dist && tsc && cp -R public/** dist",
Done

2023-06-26 10:50 UTC, nenuadrian commented
> A fix is needed in the server package.json. I think it would be nice if the tests were ported over and the change in score added back in too.

Tests are still there right? 
![image](https://github.com/google-marketing-solutions/tagspeed_audit/assets/5632882/e71249db-c132-4eed-988f-95463c982cc0)

2023-06-27 11:24 UTC, nenuadrian commented on ui/src/app/app.component.spec.ts
The tests were all backend centric and are still there I believe

2023-06-27 11:25 UTC, nenuadrian commented on ui/src/app/app.component.html
> +          <ng-container matColumnDef="lcp">
Fixed - added them via backend this time

2023-06-27 11:36 UTC, nenuadrian reviewed
Ack

2023-06-27 14:21 UTC, adamread approved these changes
LGTM

2023-06-27 15:52 UTC, merged